spring.application.name=Doctor
spring.amqp.listener.simple.acknowledgement-mode=manual
spring.amqp.host=localhost
spring.amqp.port =5672
spring.amqp.username=guest
spring.amqp.password=guest
server.port=8081
